In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier

In [5]:
data = pd.read_csv("../dataset/mnist_train_small.csv").values



print(data)

[[   0    0    0 ...    0    0    0]
 [   1    4    0 ...    0    0    0]
 [   2    1    0 ...    0    0    0]
 ...
 [7997    5    0 ...    0    0    0]
 [7998    4    0 ...    0    0    0]
 [7999    0    0 ...    0    0    0]]


In [6]:
X, Y = data[:, 2:], data[:, 1]

In [7]:
split = 5000

X_train, Y_train, X_test, Y_test = X[:split], Y[:split], X[split:], Y[split:]

In [11]:
model = KNeighborsClassifier(n_neighbors=4)

In [12]:
model.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=4, p=2,
           weights='uniform')

In [18]:
print(model.predict(X_test))
print(Y_test[0:3])

[3]
[3 4 6]
